init app theme
D-Golovanov/surf-flutter-courses pull request #6
Opened 2023-08-21 22:56 UTC by D-Golovanov

2023-09-19 20:50 UTC, samir-a-ts commented on lib/03_theme/core/theme/src/app_theme.dart
> +          textStyle: const TextStyle().copyWith(
Так делать незачем - просто передавай все параметры напрямую в класс)

2023-09-20 06:05 UTC, D-Golovanov commented on lib/03_theme/core/theme/src/app_theme.dart
> +          textStyle: const TextStyle().copyWith(
@samir-a-ts мне показалось, что понятнее сделать так. Если сделать все параметры в конструкторе, тогда в файле "theme_model.dart" на 33 строке в методе "ThemeData getThemeData()" придется прокидывать кучу цветов, а не просто схему + выбрать "темная/светлая".
или я не про то думаю?

2023-09-29 13:18 UTC, mpkander commented on lib/03_theme/core/theme/src/app_theme.dart
> +          textStyle: const TextStyle().copyWith(
> @samir-a-ts мне показалось, что понятнее сделать так. Если сделать все параметры в конструкторе, тогда в файле "theme_model.dart" на 33 строке в методе "ThemeData getThemeData()" придется прокидывать кучу цветов, а не просто схему + выбрать "темная/светлая". или я не про то думаю?

Самир имел в виду, что конструкция `const TextStyle().copyWith(` не имеет смысла, потому что TextStyle и так пустой. То есть можно просто использовать TextStyle без copyWith-метода

2023-09-29 13:31 UTC, mpkander requested changes

2023-09-29 13:31 UTC, mpkander commented on lib/03_theme/features/profile/data/models/theme_model.dart
> +    GetIt.I<IThemeRepository>().setTheme(_theme);
Крайне не рекомендую использовать GetIt именно так. На текущем этапе вы можете и не замечать, что тут что-то не так, но со временем проблема неявного использования зависимостей класса может стать большой проблемой в крупном проекте: 
1) Это крайне тяжело тестировать. Когда вы впервые столкнётесь с Unit-тестами, вы поймёте, что не сможете замокать класс: https://docs.flutter.dev/cookbook/testing/unit/mocking 
2) GetIt по своей природе является сервис локатором. Сервис локатор — это анти-паттерн, с которым очень тяжело бороться в больших проектах 

Что делать вместо? 
1) Не использовать сервис локатор напрямую в классах. Зависимости классам нужно передавать через конструктор.
2) Вы можете использовать GetIt, но исключительно для хранения общих зависимостей приложения. 

Подробнее: 
1) https://www.baeldung.com/cs/dependency-injection-vs-service-locator 
2) https://deviq.com/antipatterns/service-locator

2023-09-29 13:31 UTC, mpkander commented on lib/03_theme/features/profile/data/repository/theme_repository_sh_pref_impl.dart
> +  Future<String> getScheme() async {
Здесь гораздо правильнее использовать не строку, а что-нибудь связанное с ограниченным числом значений: enum или sealed-класс. Это гораздо надёжнее

2023-09-29 13:31 UTC, mpkander commented on lib/03_theme/features/profile/data/repository/theme_repository_sh_pref_impl.dart
> +  Future<String> getScheme() async {
Это же касается и theme

2023-09-29 13:37 UTC, samir-a-ts commented on lib/03_theme/main.dart
> +import 'package:flutter/material.dart';
В этом файле отмечу 2 проблемы:

- лучше выносить инициализацию зависимостей в getIt в отдельный метод - код чище
- Использовать все возможности getIt - вместо того, чтобы ждать инициализации SharedPreferences, ты можешь использовать метод `registerSingletonAsync` и потом его использовать после инициализации всех моделей (`allReady`)
- Не стоит инициализировать обьекты бизнес-логики (модельки, блок и тп) внутри виджетов - лучше это, опять же, делать тут же

Вот код, что у меня получился:



```dart

final injector = GetIt.instance;

Future<void> initializeInjection() async {
  injector.registerSingletonAsync(
    () => SharedPreferences.getInstance(),
  );

  await injector.allReady();

  injector.registerSingleton<IThemeRepository>(
    ThemeRepositoryShPrefImpl(
      pref: injector.get(),
    ),
  );

  injector.registerSingleton<ThemeModel>(
    ThemeModel(injector.get()),
  );
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await initializeInjection();

  runApp(const ThemeChangeApp());
}

```

2023-09-29 13:45 UTC, samir-a-ts commented on lib/03_theme/theme_change_app.dart
> +  final _themeModel = ThemeModel();
Тут дело в том, что при первой инициализации ты не подгружаешь тему и схему из кэша - используется та, что уже тобой указана в модельке. Если ты бы всё-таки хотел, чтобы оно подгружалось, то вот) :

Дополнительно отмечу:

- отдельные страницы лучше всего помечать `Screen`, не просто оставлять `Profile` - трактовать это можно по разному - просто шапка, целый экран, маленький виджет с фото и тп
- В своей реализации ты представляешь типы тем как строки - не очень хорошая практика - на проект, например, может прийти другой человек, что не знает всех тип тем + ты сам можешь забыть) Либо отмечай в комментариях типы (что уже получше, но все еще не идеально), либо используй `enum` - он не только удобный, но и предоставляет возможность использовать всякие фишки языка по типу `switch`
- Функция сборки `ThemeData` в `ThemeModel` показалась мне слегка громоздкой - её можно изрядно упростить, пример ниже)

```dart
class _ThemeChangeAppState extends State<ThemeChangeApp> with WidgetsBindingObserver {
  final ThemeModel _themeModel = injector();

  @override
  void initState() {
    super.initState();

    WidgetsBinding.instance.addObserver(this);

    _themeModel.loadThemeFromCache();
  }

  @override
  void didChangePlatformBrightness() {
    super.didChangePlatformBrightness();

    _themeModel.setThemeFromBrightness(
      SchedulerBinding.instance.platformDispatcher.platformBrightness,
    );
  }

  @override
  Widget build(BuildContext ctx) {
    final userGettingBefore = UserProfileModel(
      name: 'Маркус Хассельборг',
      email: 'MarkusHSS@gmail.com',
      birth: DateTime(1986, 3, 3),
      team: 'Сборная Швеции',
      position: 'Скип',
      avatar:
          'https://w7.pngwing.com/pngs/700/759/png-transparent-avatars-accounts-man-male-people-person-glasses-broken-hoodie-male-avatars-free-d-illustration.png',
      awards: ['🥇', '🥇', '🥉', '🥈', '🥉'],
    );

    return ChangeNotifierProvider(
      model: _themeModel,
      child: Builder(builder: (context) {
        return MaterialApp(
          debugShowCheckedModeBanner: false,
          home: ProfileScreen(
            user: userGettingBefore,
          ),
          theme: ChangeNotifierProvider.watch<ThemeModel>(context)!.getThemeData(),
        );
      }),
    );
  }
}

```

```dart

class ThemeModel extends ChangeNotifier {
  final IThemeRepository _themeRepository;

  ThemeModel(this._themeRepository);

  Future<void> loadThemeFromCache() async {
    final themeMode = await _themeRepository.getTheme();
    final schemeMode = await _themeRepository.getScheme();

    setTheme(themeMode);
    setScheme(schemeMode);
  }

  AppThemeMode _theme = AppThemeMode.system;
  AppSchemeMode _scheme = AppSchemeMode.green;

  Future<void> setThemeFromBrightness(Brightness brightness) async {
    final theme = switch (brightness) {
      Brightness.dark => AppThemeMode.dark,
      Brightness.light => AppThemeMode.light,
    };

    if (theme == _theme) return;

    _theme = theme;

    await _themeRepository.setTheme(_theme);

    notifyListeners();
  }

  Future<void> setTheme(AppThemeMode newTheme) async {
    if (newTheme == _theme) return;

    _theme = newTheme;

    await _themeRepository.setTheme(_theme);

    notifyListeners();
  }

  Future<void> setScheme(AppSchemeMode newScheme) async {
    if (newScheme == _scheme) return;

    _scheme = newScheme;

    await _themeRepository.setScheme(_scheme);

    notifyListeners();
  }

  AppThemeMode get theme => _theme;

  AppSchemeMode get scheme => _scheme;

  ThemeData getThemeData() {
    var brightness = SchedulerBinding.instance.platformDispatcher.platformBrightness;

    switch (_theme) {
      case AppThemeMode.system:
        break;
      case AppThemeMode.light:
        brightness = Brightness.light;
        break;
      case AppThemeMode.dark:
        brightness = Brightness.dark;
        break;
    }

    SchemeColor? scheme;

    switch (this.scheme) {
      case AppSchemeMode.green:
        scheme = GreenSchemeColor();
        break;
      case AppSchemeMode.blue:
        scheme = BlueSchemeColor();
        break;
      case AppSchemeMode.orange:
        scheme = OrangeSchemeColor();
        break;
    }

    final themeData = AppTheme(scheme: scheme);

    switch (brightness) {
      case Brightness.dark:
        return themeData.darkThemeData;
      case Brightness.light:
        return themeData.ligthThemeData;
    }
  }
}

```

2023-09-29 13:48 UTC, samir-a-ts commented on lib/03_theme/features/profile/presentation/widgets/scheme_buttons_widget.dart
> +                  ChangeNotifierProvider.read<ThemeModel>(context)!.getScheme();
- Не перенасыщай код лишними вызовами метода read - учти, что это довольно дорогая операция по поиску элемента в дереве, в таком маленьком проекте это может быть не критично, но в проектах побольше уже может вызывать проблемы)
- Не используй одно и то же выражение (`schemeButtonList[index]`) по коду, лучше не повторяться - вынеси в отдельную переменную, так будет проще)

```dart

class SchemeButtonsWidget extends StatelessWidget {
  const SchemeButtonsWidget({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    final schemeButtonList = [
      SchemeModel(
        schemeMode: AppSchemeMode.green,
        iconPath: 'assets/images/icon_scheme_green.svg',
      ),
      SchemeModel(
        schemeMode: AppSchemeMode.blue,
        iconPath: 'assets/images/icon_scheme_blue.svg',
      ),
      SchemeModel(
        schemeMode: AppSchemeMode.orange,
        iconPath: 'assets/images/icon_scheme_orange.svg',
      ),
    ];

    final themeModel = ChangeNotifierProvider.watch<ThemeModel>(context)!;

    final theme = Theme.of(context);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const SizedBox(height: 8),
        Text(
          'Цветовая схема',
          style: context.textStyle.hintText,
        ),
        const SizedBox(height: 16),
        SizedBox(
          height: 66,
          child: ListView.separated(
            scrollDirection: Axis.horizontal,
            itemCount: schemeButtonList.length,
            itemBuilder: (context, index) {
              final schemeButton = schemeButtonList[index];

              bool isSelected = schemeButton.schemeMode == themeModel.scheme;

              return GestureDetector(
                onTap: () {
                  ChangeNotifierProvider.read<ThemeModel>(context)!.setScheme(
                    schemeButtonList[index].schemeMode,
                  );
                },
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 30, vertical: 10),
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(6),
                    color: context.color.schemeButtonBackground,
                    border: isSelected
                        ? Border.all(
                            width: 1,
                            color: theme.primaryColor,
                          )
                        : null,
                  ),
                  child: Column(
                    children: [
                      SvgPicture.asset(schemeButtonList[index].iconPath),
                      const SizedBox(height: 4),
                      Text(
                        'Схема ${index + 1}',
                        style: theme.textTheme.bodySmall!.copyWith(
                          color: isSelected ? null : context.color.schemeButtonTextNotSelected,
                        ),
                      ),
                    ],
                  ),
                ),
              );
            },
            separatorBuilder: (context, index) {
              return const SizedBox(width: 12);
            },
          ),
        ),
        const SizedBox(height: 8),
      ],
    );
  }
}


```

2023-09-29 13:49 UTC, samir-a-ts commented on lib/03_theme/features/profile/presentation/widgets/bottom_sheet_widget.dart
> +                ChangeNotifierProvider.read<ThemeModel>(context)!
Опять же - не нужно 2 раза проходить по дереву в поиске этого виджета

2023-09-29 13:51 UTC, samir-a-ts commented on lib/03_theme/features/profile/presentation/widgets/bottom_sheet_widget.dart
> +              if (ChangeNotifierProvider.watch<ThemeModel>(context)!
Лишний аргумент в сторону `enum` - запутаться будет намного сложнее)

+ проверяйте написание названия классов, мелочь, а приятно)

```dart

class _BodyBottomSheetState extends State<BodyBottomSheet> {
  late AppThemeMode prevTheme;
  late AppSchemeMode prevScheme;

  @override
  void initState() {
    final themeModel = ChangeNotifierProvider.read<ThemeModel>(context)!;

    prevTheme = themeModel.theme;
    prevScheme = themeModel.scheme;

    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    final themeModel = ChangeNotifierProvider.watch<ThemeModel>(context)!;

    return Wrap(
      children: [
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 20).copyWith(
            top: 8,
            bottom: 24,
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const TitleBottomSheet(),
              const SizedBox(height: 8),
              RadioListTileWidget(
                title: 'Системная',
                value: AppThemeMode.system,
                group: widget.currentThemeGroup,
              ),
              RadioListTileWidget(
                title: 'Светлая',
                value: AppThemeMode.light,
                group: widget.currentThemeGroup,
              ),
              if (themeModel.theme == AppThemeMode.light) const SchemeButtonsWidget(),
              RadioListTileWidget(
                title: 'Темная',
                value: AppThemeMode.dark,
                group: widget.currentThemeGroup,
              ),
              if (themeModel.theme == AppThemeMode.dark) const SchemeButtonsWidget(),
              const SizedBox(height: 24),
              ElevatedButton(
                onPressed: () {
                  Navigator.of(context).pop();
                },
                child: const Text('Готово'),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

```

2023-09-29 13:53 UTC, samir-a-ts commented on lib/03_theme/features/profile/domain/repository/theme_repository.dart
> +abstract interface class IThemeRepository {
Если уж и создаёте интерфейс - по хорошему к нему нужно добавить подробные комментарии + в твоей реализации репозиторий можно заменить на инстанцию SharedPreferences и ничего в целом не изменится, а это плохо - чтобы добавить репозиторию смысла, он должен хотя-бы немного, но трансформировать сырые данные в какие-либо модельки, с которыми мы можем уже работать:

```dart

/// Interface, which describes logic for
/// handling themes and schemes of an app.
abstract interface class IThemeRepository {
  /// Get currently saved theme.
  ///
  /// Options are: 'system', 'light', 'dark'
  Future<AppThemeMode> getTheme();

  /// Saves given theme mode in cache.
  ///
  /// This value would be automatically
  /// loaded later on.
  Future<void> setTheme(AppThemeMode theme);

  /// Get currently saved theme.
  ///
  /// Options are: 'green', 'blue', 'orange'
  Future<AppSchemeMode> getScheme();

  /// Saves given scheme mode in cache.
  ///
  /// This value would be automatically
  /// loaded later on.
  Future<void> setScheme(AppSchemeMode scheme);
}

```

2023-09-29 13:54 UTC, samir-a-ts commented on lib/03_theme/features/profile/domain/entities/theme_entity.dart
> +class ThemeEntity {
Такие модельки используются только для отображения, они не являются компонентами бизнес-логики, поэтому сюда их заносить неуместно, я считаю - лучше в файл с виджетом

2023-10-04 20:07 UTC, D-Golovanov commented on lib/03_theme/features/profile/data/repository/theme_repository_sh_pref_impl.dart
> +  Future<String> getScheme() async {
самое смешное, что у меня же в модели созданы были енамы🤦‍♂️
`enum CurrentTheme { system, light, dark }`
`enum CurrentScheme { green, blue, orange }`

2023-10-11 22:37 UTC, merged